import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, ArrowDownToLine, Boxes, Download, Plus, Save, Truck } from 'lucide-react';
import { supabase } from '../supabaseClient.js';
import { useNegocio } from '../context/NegocioContext.jsx';
import { useUI } from '../components/ui/UI.jsx';
import { exportarCSV } from '../utils/exportar.js';
import { entradaNumerica, fechaLocalISO, LIMITES, limpiarTexto, numeroSeguro, telefonoMX, textoParaGuardar } from '../utils/seguridad.js';

const money=n=>`$${(Number(n)||0).toLocaleString('es-MX',{minimumFractionDigits:2})}`;
const num=n=>Number(n)||0;
const input='w-full p-3 bg-slate-50 rounded-xl border border-slate-100 font-bold text-slate-700 outline-none focus:ring-2 focus:ring-primario/10';

export default function Inventario({session}){
 const {negocioId}=useNegocio();const {toast}=useUI();const [items,setItems]=useState([]),[proveedores,setProveedores]=useState([]),[movs,setMovs]=useState([]);const [item,setItem]=useState({nombre:'',sku:'',unidad:'pieza',minimo:'',costo:'',proveedor_id:''});const [proveedor,setProveedor]=useState({nombre:'',telefono:'',contacto:''});const [mov,setMov]=useState({item_id:'',tipo:'entrada',cantidad:'',nota:''});
 const cargar=useCallback(async()=>{if(!negocioId)return;const[i,p,m]=await Promise.all([supabase.from('almacen_articulos').select('*').eq('negocio_id',negocioId).eq('activo',true).order('nombre'),supabase.from('almacen_proveedores').select('*').eq('negocio_id',negocioId).order('nombre'),supabase.from('almacen_movimientos').select('*, almacen_articulos(nombre)').eq('negocio_id',negocioId).order('created_at',{ascending:false}).limit(30)]);const error=[i,p,m].find(x=>x.error);if(error)return toast.error(error.error.message);setItems(i.data||[]);setProveedores(p.data||[]);setMovs(m.data||[]);},[negocioId,toast]);useEffect(()=>{cargar();},[cargar]);const bajos=useMemo(()=>items.filter(i=>num(i.existencias)<=num(i.minimo)),[items]);
 const guardarItem=async e=>{e.preventDefault();const nombre=textoParaGuardar(item.nombre,LIMITES.descripcion);if(!nombre)return toast.error('Escribe el material o producto.');const{error}=await supabase.from('almacen_articulos').insert([{negocio_id:negocioId,nombre,sku:textoParaGuardar(item.sku,50)||null,unidad:textoParaGuardar(item.unidad,LIMITES.unidad)||'pieza',minimo:numeroSeguro(item.minimo),costo:numeroSeguro(item.costo),proveedor_id:item.proveedor_id||null}]);if(error)return toast.error(error.message);setItem({nombre:'',sku:'',unidad:'pieza',minimo:'',costo:'',proveedor_id:''});toast.ok('Material agregado.');cargar();};
 const guardarProveedor=async e=>{e.preventDefault();const nombre=textoParaGuardar(proveedor.nombre,LIMITES.proveedor);if(!nombre)return toast.error('Escribe el proveedor.');const{error}=await supabase.from('almacen_proveedores').insert([{negocio_id:negocioId,nombre,telefono:telefonoMX(proveedor.telefono)||null,contacto:textoParaGuardar(proveedor.contacto,LIMITES.nombre)||null}]);if(error)return toast.error(error.message);setProveedor({nombre:'',telefono:'',contacto:''});toast.ok('Proveedor guardado.');cargar();};
 const guardarMov=async e=>{e.preventDefault();const actual=items.find(i=>i.id===mov.item_id),cantidad=numeroSeguro(mov.cantidad);if(!actual||cantidad<=0)return toast.error('Selecciona material y cantidad válida.');const delta=mov.tipo==='salida'?-cantidad:cantidad;if(num(actual.existencias)+delta<0)return toast.error('No hay existencias suficientes.');const{error:merr}=await supabase.from('almacen_movimientos').insert([{negocio_id:negocioId,articulo_id:actual.id,user_id:session.user.id,tipo:mov.tipo,cantidad,nota:textoParaGuardar(mov.nota,LIMITES.nota)||null,fecha:fechaLocalISO()}]);if(merr)return toast.error(merr.message);const{error}=await supabase.from('almacen_articulos').update({existencias:num(actual.existencias)+delta}).eq('id',actual.id);if(error)return toast.error(error.message);setMov({item_id:'',tipo:'entrada',cantidad:'',nota:''});toast.ok('Movimiento registrado.');cargar();};
 const exportar=()=>{if(!items.length)return toast.warn('No hay materiales para exportar.');exportarCSV('inventario',[{label:'Material',valor:i=>i.nombre},{label:'Código',valor:i=>i.sku||''},{label:'Unidad',valor:i=>i.unidad},{label:'Existencias',valor:i=>i.existencias},{label:'Mínimo',valor:i=>i.minimo},{label:'Costo',valor:i=>num(i.costo).toFixed(2)},{label:'Estado',valor:i=>num(i.existencias)<=num(i.minimo)?'Reponer':'Disponible'}],items);toast.ok('Inventario exportado.');};
 return <div className="p-4 md:p-8 max-w-7xl mx-auto space-y-6"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-2xl md:text-3xl font-black text-slate-800 uppercase tracking-tighter flex gap-3 items-center"><Boxes className="text-primario"/> Inventario y proveedores</h2><p className="text-sm font-medium text-slate-500">Materiales, existencias, mínimos y movimientos para evitar compras urgentes.</p></div><button onClick={exportar} className="bg-white border px-4 py-2.5 rounded-xl text-xs font-black text-slate-600 hover:text-primario"><Download size={15} className="inline mr-1"/>Exportar CSV</button></div>{bajos.length>0&&<div className="bg-amber-50 border border-amber-200 rounded-2xl p-4 text-amber-800 font-bold flex gap-2"><AlertTriangle/> {bajos.length} material(es) requieren reposición: {bajos.map(i=>i.nombre).join(', ')}</div>}
 <div className="grid xl:grid-cols-3 gap-6"><form onSubmit={guardarItem} className="bg-white p-5 rounded-3xl border space-y-3"><h3 className="font-black flex gap-2"><Plus size={18}/> Nuevo material</h3><input maxLength={LIMITES.descripcion} className={input} value={item.nombre} onChange={e=>setItem({...item,nombre:limpiarTexto(e.target.value,LIMITES.descripcion)})} placeholder="Ej. Cable THW calibre 12"/><div className="grid grid-cols-2 gap-2"><input maxLength="50" className={input} value={item.sku} onChange={e=>setItem({...item,sku:limpiarTexto(e.target.value,50)})} placeholder="Código"/><input maxLength={LIMITES.unidad} className={input} value={item.unidad} onChange={e=>setItem({...item,unidad:limpiarTexto(e.target.value,LIMITES.unidad)})} placeholder="Unidad"/></div><div className="grid grid-cols-2 gap-2"><input className={input} inputMode="decimal" value={item.minimo} onChange={e=>setItem({...item,minimo:entradaNumerica(e.target.value)})} placeholder="Mínimo"/><input className={input} inputMode="decimal" value={item.costo} onChange={e=>setItem({...item,costo:entradaNumerica(e.target.value)})} placeholder="Costo unitario"/></div><select className={input} value={item.proveedor_id} onChange={e=>setItem({...item,proveedor_id:e.target.value})}><option value="">Sin proveedor</option>{proveedores.map(p=><option key={p.id} value={p.id}>{p.nombre}</option>)}</select><button className="w-full bg-primario text-white p-3 rounded-xl font-bold"><Save size={16} className="inline mr-2"/>Guardar material</button></form>
 <form onSubmit={guardarMov} className="bg-white p-5 rounded-3xl border space-y-3"><h3 className="font-black flex gap-2"><ArrowDownToLine size={18}/> Entrada / salida</h3><select className={input} value={mov.item_id} onChange={e=>setMov({...mov,item_id:e.target.value})}><option value="">Selecciona material</option>{items.map(i=><option key={i.id} value={i.id}>{i.nombre} ({i.existencias} {i.unidad})</option>)}</select><select className={input} value={mov.tipo} onChange={e=>setMov({...mov,tipo:e.target.value})}><option value="entrada">Entrada / compra</option><option value="salida">Salida / uso en trabajo</option><option value="ajuste">Ajuste de inventario</option></select><input className={input} inputMode="decimal" value={mov.cantidad} onChange={e=>setMov({...mov,cantidad:entradaNumerica(e.target.value)})} placeholder="Cantidad"/><input maxLength={LIMITES.nota} className={input} value={mov.nota} onChange={e=>setMov({...mov,nota:limpiarTexto(e.target.value,LIMITES.nota)})} placeholder="Trabajo, factura o motivo"/><button className="w-full bg-slate-900 text-white p-3 rounded-xl font-bold">Registrar movimiento</button></form>
 <form onSubmit={guardarProveedor} className="bg-white p-5 rounded-3xl border space-y-3"><h3 className="font-black flex gap-2"><Truck size={18}/> Nuevo proveedor</h3><input maxLength={LIMITES.proveedor} className={input} value={proveedor.nombre} onChange={e=>setProveedor({...proveedor,nombre:limpiarTexto(e.target.value,LIMITES.proveedor)})} placeholder="Nombre o empresa"/><input maxLength={LIMITES.nombre} className={input} value={proveedor.contacto} onChange={e=>setProveedor({...proveedor,contacto:limpiarTexto(e.target.value,LIMITES.nombre)})} placeholder="Contacto"/><input maxLength="12" inputMode="numeric" className={input} value={proveedor.telefono} onChange={e=>setProveedor({...proveedor,telefono:telefonoMX(e.target.value)})} placeholder="Teléfono"/><button className="w-full bg-slate-100 text-slate-700 p-3 rounded-xl font-bold">Guardar proveedor</button></form></div>
 <div className="grid lg:grid-cols-2 gap-6"><div className="bg-white p-5 rounded-3xl border"><h3 className="font-black mb-3">Existencias</h3>{items.map(i=><div key={i.id} className="flex justify-between p-3 bg-slate-50 rounded-xl mb-2"><div><p className="font-bold">{i.nombre}</p><p className="text-xs text-slate-400">{i.sku||'Sin código'} · mín. {i.minimo} · {money(i.costo)}</p></div><p className={`font-black ${num(i.existencias)<=num(i.minimo)?'text-amber-600':'text-emerald-600'}`}>{i.existencias} {i.unidad}</p></div>)}</div><div className="bg-white p-5 rounded-3xl border"><h3 className="font-black mb-3">Últimos movimientos</h3>{movs.map(m=><div key={m.id} className="flex justify-between p-3 bg-slate-50 rounded-xl mb-2"><p className="font-bold text-sm">{m.almacen_articulos?.nombre||'Material'}<span className="block text-xs text-slate-400">{m.nota||m.tipo}</span></p><p className={m.tipo==='salida'?'text-rose-600 font-black':'text-emerald-600 font-black'}>{m.tipo==='salida'?'−':'+'}{m.cantidad}</p></div>)}</div></div></div>;
}
