import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowRight, CalendarDays, Download, Edit3, Plus, Save, Search, Target, Trash2, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '../supabaseClient.js';
import { useNegocio } from '../context/NegocioContext.jsx';
import { useUI } from '../components/ui/UI.jsx';
import { entradaNumerica, fechaLocalISO, limpiarTexto, numeroSeguro, textoParaGuardar } from '../utils/seguridad.js';
import { exportarCSV } from '../utils/exportar.js';

const VACIA = { nombre:'', cliente_id:'', contacto:'', telefono:'', correo:'', origen:'referido', etapa:'nuevo', monto_estimado:'', probabilidad:'30', proximo_contacto:'', notas:'', motivo_perdida:'' };
const ETAPAS = { nuevo:{ etiqueta:'Nuevo', color:'bg-slate-100 text-slate-600' }, contactado:{ etiqueta:'Contactado', color:'bg-blue-100 text-blue-700' }, cotizado:{ etiqueta:'Cotizado', color:'bg-violet-100 text-violet-700' }, negociacion:{ etiqueta:'Negociación', color:'bg-amber-100 text-amber-700' }, ganado:{ etiqueta:'Ganado', color:'bg-emerald-100 text-emerald-700' }, perdido:{ etiqueta:'Perdido', color:'bg-rose-100 text-rose-700' } };
const money = n => `$${(Number(n)||0).toLocaleString('es-MX',{minimumFractionDigits:2})}`;
const input = 'w-full p-3 bg-slate-50 rounded-xl border border-slate-100 font-bold text-slate-700 outline-none focus:bg-white focus:ring-2 focus:ring-primario/10';

export default function Oportunidades({ session }) {
  const { negocioId, puede } = useNegocio(); const { toast, confirmar } = useUI(); const navigate = useNavigate();
  const [oportunidades,setOportunidades]=useState([]), [clientes,setClientes]=useState([]), [form,setForm]=useState(VACIA), [editando,setEditando]=useState(null), [busqueda,setBusqueda]=useState(''), [etapaFiltro,setEtapaFiltro]=useState('todas'), [cargando,setCargando]=useState(false);
  const cargar=useCallback(async()=>{ if(!negocioId)return; const [o,c]=await Promise.all([supabase.from('oportunidades').select('*').eq('negocio_id',negocioId).order('updated_at',{ascending:false}).limit(1000),supabase.from('clientes').select('id,nombre,alias,telefono,correo').eq('negocio_id',negocioId).order('nombre').limit(2000)]); if(o.error)toast.error('No se pudieron cargar oportunidades: '+o.error.message); else setOportunidades(o.data||[]); setClientes(c.data||[]); },[negocioId,toast]);
  useEffect(()=>{cargar();},[cargar]);
  const clientesPorId=useMemo(()=>Object.fromEntries(clientes.map(c=>[c.id,c])),[clientes]);
  const lista=useMemo(()=>oportunidades.filter(o=>(etapaFiltro==='todas'||o.etapa===etapaFiltro)&&(`${o.nombre} ${o.contacto||''} ${o.telefono||''}`.toLowerCase().includes(busqueda.toLowerCase()))),[oportunidades,etapaFiltro,busqueda]);
  const resumen=useMemo(()=>{const abiertas=oportunidades.filter(o=>!['ganado','perdido'].includes(o.etapa)); return {abiertas, estimado:abiertas.reduce((a,o)=>a+numeroSeguro(o.monto_estimado),0), ponderado:abiertas.reduce((a,o)=>a+numeroSeguro(o.monto_estimado)*numeroSeguro(o.probabilidad)/100,0), seguimientos:abiertas.filter(o=>o.proximo_contacto&&o.proximo_contacto<=fechaLocalISO()).length};},[oportunidades]);
  const seleccionarCliente=id=>{const c=clientesPorId[id]; setForm(f=>({...f,cliente_id:id,nombre:c?.nombre||f.nombre,contacto:c?.alias||f.contacto,telefono:c?.telefono||f.telefono,correo:c?.correo||f.correo}));};
  const guardar=async e=>{e.preventDefault(); const nombre=textoParaGuardar(form.nombre,120); if(!nombre)return toast.error('Escribe el nombre de la oportunidad o negocio.'); if(cargando)return; setCargando(true); const datos={nombre,cliente_id:form.cliente_id||null,contacto:textoParaGuardar(form.contacto,100)||null,telefono:textoParaGuardar(form.telefono,30)||null,correo:textoParaGuardar(form.correo,120).toLowerCase()||null,origen:form.origen,etapa:form.etapa,monto_estimado:numeroSeguro(form.monto_estimado),probabilidad:Math.max(0,Math.min(100,Math.round(numeroSeguro(form.probabilidad)))),proximo_contacto:form.proximo_contacto||null,notas:textoParaGuardar(form.notas,1500,{multilinea:true})||null,motivo_perdida:form.etapa==='perdido'?textoParaGuardar(form.motivo_perdida,300)||null:null,updated_at:new Date().toISOString()}; const q=editando?supabase.from('oportunidades').update(datos).eq('id',editando):supabase.from('oportunidades').insert([{...datos,negocio_id:negocioId,user_id:session.user.id}]); const {error}=await q; setCargando(false); if(error)return toast.error(error.message); toast.ok(editando?'Oportunidad actualizada.':'Oportunidad registrada.'); setForm(VACIA);setEditando(null);cargar();};
  const editar=o=>{setEditando(o.id);setForm({nombre:o.nombre||'',cliente_id:o.cliente_id||'',contacto:o.contacto||'',telefono:o.telefono||'',correo:o.correo||'',origen:o.origen||'referido',etapa:o.etapa||'nuevo',monto_estimado:String(o.monto_estimado||''),probabilidad:String(o.probabilidad??30),proximo_contacto:o.proximo_contacto||'',notas:o.notas||'',motivo_perdida:o.motivo_perdida||''});window.scrollTo({top:0,behavior:'smooth'});};
  const eliminar=async o=>{if(!await confirmar({titulo:'Eliminar oportunidad',mensaje:`Se eliminará “${o.nombre}”.`,okTexto:'Eliminar',peligro:true}))return;const {error}=await supabase.from('oportunidades').delete().eq('id',o.id);if(error)return toast.error(error.message);toast.ok('Oportunidad eliminada.');cargar();};
  const cambiarEtapa=async(o,etapa)=>{const {error}=await supabase.from('oportunidades').update({etapa,updated_at:new Date().toISOString()}).eq('id',o.id);if(error)return toast.error(error.message);cargar();};
  const crearCotizacion=o=>navigate('/presupuestos',{state:{oportunidadOrigen:{id:o.id,clienteId:o.cliente_id,cliente:clientesPorId[o.cliente_id]?.nombre||o.nombre}}});
  const exportar=()=>{if(!lista.length)return toast.warn('No hay oportunidades para exportar.');exportarCSV('embudo_comercial',[{label:'Oportunidad',valor:o=>o.nombre},{label:'Etapa',valor:o=>ETAPAS[o.etapa]?.etiqueta||o.etapa},{label:'Monto estimado',valor:o=>numeroSeguro(o.monto_estimado).toFixed(2)},{label:'Probabilidad',valor:o=>`${o.probabilidad}%`},{label:'Próximo contacto',valor:o=>o.proximo_contacto||''},{label:'Origen',valor:o=>o.origen},{label:'Contacto',valor:o=>o.contacto||''}],lista);toast.ok('Embudo exportado a CSV.');};
  return <div className="p-4 md:p-8 max-w-7xl mx-auto space-y-6"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-2xl md:text-3xl font-black text-slate-800 uppercase tracking-tighter flex gap-3 items-center"><Target className="text-primario"/> Oportunidades</h2><p className="text-sm font-medium text-slate-500">Embudo comercial, próximos pasos y previsión de ventas.</p></div><div className="flex gap-2 text-xs font-black"><span className="bg-slate-100 px-3 py-2 rounded-xl">{resumen.abiertas.length} abiertas</span><span className="bg-emerald-50 text-emerald-700 px-3 py-2 rounded-xl">{money(resumen.ponderado)} probable</span><button onClick={exportar} className="bg-white border px-3 py-2 rounded-xl text-slate-600 hover:text-primario"><Download size={14} className="inline mr-1"/>CSV</button></div></div>
    <div className="grid grid-cols-2 md:grid-cols-4 gap-3"><Resumen label="Abiertas" valor={resumen.abiertas.length}/><Resumen label="Valor en proceso" valor={money(resumen.estimado)}/><Resumen label="Pronóstico ponderado" valor={money(resumen.ponderado)}/><Resumen label="Seguimientos vencidos" valor={resumen.seguimientos} alerta={resumen.seguimientos>0}/></div>
    <div className="grid xl:grid-cols-3 gap-6"><form onSubmit={guardar} className="bg-white border p-5 rounded-3xl space-y-3 h-fit"><h3 className="font-black flex gap-2 items-center"><Plus size={18}/>{editando?'Editar oportunidad':'Nueva oportunidad'}</h3><input className={input} value={form.nombre} onChange={e=>setForm({...form,nombre:limpiarTexto(e.target.value,120)})} placeholder="Empresa, cliente o trabajo *"/><select className={input} value={form.cliente_id} onChange={e=>seleccionarCliente(e.target.value)}><option value="">Vincular cliente existente (opcional)</option>{clientes.map(c=><option key={c.id} value={c.id}>{c.nombre}{c.alias?` · ${c.alias}`:''}</option>)}</select><div className="grid grid-cols-2 gap-2"><input className={input} value={form.contacto} onChange={e=>setForm({...form,contacto:limpiarTexto(e.target.value,100)})} placeholder="Contacto"/><input className={input} value={form.telefono} onChange={e=>setForm({...form,telefono:limpiarTexto(e.target.value,30)})} placeholder="Teléfono"/></div><div className="grid grid-cols-2 gap-2"><select className={input} value={form.etapa} onChange={e=>setForm({...form,etapa:e.target.value})}>{Object.entries(ETAPAS).map(([id,x])=><option key={id} value={id}>{x.etiqueta}</option>)}</select><select className={input} value={form.origen} onChange={e=>setForm({...form,origen:e.target.value})}>{['referido','redes','web','llamada','visita','otro'].map(x=><option key={x} value={x}>{x[0].toUpperCase()+x.slice(1)}</option>)}</select></div><div className="grid grid-cols-3 gap-2"><input className={input} inputMode="decimal" value={form.monto_estimado} onChange={e=>setForm({...form,monto_estimado:entradaNumerica(e.target.value)})} placeholder="Monto"/><input className={input} inputMode="numeric" value={form.probabilidad} onChange={e=>setForm({...form,probabilidad:e.target.value.replace(/\D/g,'').slice(0,3)})} placeholder="%"/><input className={input} type="date" value={form.proximo_contacto} onChange={e=>setForm({...form,proximo_contacto:e.target.value})}/></div>{form.etapa==='perdido'&&<input className={input} value={form.motivo_perdida} onChange={e=>setForm({...form,motivo_perdida:limpiarTexto(e.target.value,300)})} placeholder="Motivo de pérdida"/>}<textarea className={`${input} resize-none`} rows="3" value={form.notas} onChange={e=>setForm({...form,notas:limpiarTexto(e.target.value,1500,{multilinea:true})})} placeholder="Notas y siguiente acción"/><div className="flex gap-2"><button disabled={cargando} className="flex-1 bg-primario text-white p-3 rounded-xl font-bold"><Save size={16} className="inline mr-2"/>{cargando?'Guardando...':'Guardar'}</button>{editando&&<button type="button" onClick={()=>{setEditando(null);setForm(VACIA)}} className="px-4 bg-slate-100 rounded-xl"><X size={18}/></button>}</div></form>
      <section className="xl:col-span-2 space-y-4"><div className="flex flex-wrap gap-2"><div className="relative flex-1 min-w-[220px]"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input className={`${input} pl-9`} value={busqueda} onChange={e=>setBusqueda(e.target.value)} placeholder="Buscar oportunidad o contacto"/></div><select className={`${input} w-auto`} value={etapaFiltro} onChange={e=>setEtapaFiltro(e.target.value)}><option value="todas">Todas las etapas</option>{Object.entries(ETAPAS).map(([id,x])=><option key={id} value={id}>{x.etiqueta}</option>)}</select></div>{lista.length===0?<div className="p-12 bg-white border border-dashed rounded-3xl text-center text-slate-400 font-bold">No hay oportunidades con este filtro.</div>:<div className="grid md:grid-cols-2 gap-3">{lista.map(o=>{const e=ETAPAS[o.etapa]||ETAPAS.nuevo;const vencido=o.proximo_contacto&&o.proximo_contacto<=fechaLocalISO()&&!['ganado','perdido'].includes(o.etapa);return <article key={o.id} className="bg-white border rounded-2xl p-4 space-y-3"><div className="flex justify-between gap-2"><div className="min-w-0"><h3 className="font-black text-slate-800 truncate">{o.nombre}</h3><p className="text-xs font-medium text-slate-400 truncate">{o.contacto||clientesPorId[o.cliente_id]?.nombre||'Sin contacto'} · {o.origen}</p></div><span className={`text-[10px] font-black px-2 py-1 rounded-lg h-fit ${e.color}`}>{e.etiqueta}</span></div><div className="flex justify-between text-sm"><span className="font-black text-slate-700">{money(o.monto_estimado)}</span><span className="text-slate-500 font-bold">{o.probabilidad}% probable</span></div>{o.proximo_contacto&&<p className={`text-xs font-bold flex gap-1 items-center ${vencido?'text-rose-600':'text-slate-500'}`}><CalendarDays size={13}/>{vencido?'Seguimiento vencido: ':'Próximo: '}{o.proximo_contacto.split('-').reverse().join('/')}</p>}<div className="flex flex-wrap gap-1.5 pt-1"><select value={o.etapa} onChange={ev=>cambiarEtapa(o,ev.target.value)} className="text-[11px] font-bold bg-slate-100 rounded-lg px-2"><option value={o.etapa}>{e.etiqueta}</option>{Object.entries(ETAPAS).filter(([id])=>id!==o.etapa).map(([id,x])=><option key={id} value={id}>{x.etiqueta}</option>)}</select>{!o.venta_id&&o.etapa!=='perdido'&&<button onClick={()=>crearCotizacion(o)} className="text-[11px] font-black bg-primario-suave text-primario-dark px-2 py-1.5 rounded-lg">Cotizar <ArrowRight size={12} className="inline"/></button>}<button onClick={()=>editar(o)} className="p-1.5 text-slate-500 hover:bg-slate-100 rounded-lg"><Edit3 size={14}/></button>{puede('eliminar_registros')&&<button onClick={()=>eliminar(o)} className="p-1.5 text-rose-500 hover:bg-rose-50 rounded-lg"><Trash2 size={14}/></button>}</div></article>})}</div>}</section></div></div>;
}
function Resumen({label,valor,alerta}){return <div className={`p-4 rounded-2xl border ${alerta?'bg-rose-50 border-rose-200':'bg-white'}`}><p className="text-[10px] font-black uppercase text-slate-400">{label}</p><p className={`font-black text-lg truncate ${alerta?'text-rose-600':'text-slate-800'}`}>{valor}</p></div>}
